"""install.inf + uninstall.cmd generators.

How the INF works (right-click -> Install):
  * CopyFiles  -> copies every cursor to C:\\Windows\\Cursors\\<scheme>  (dir id 10 = %windir%; needs admin/UAC)
  * Scheme.Reg -> registers the scheme in HKCU\\Control Panel\\Cursors\\Schemes so it shows in the dropdown
  * Wreg       -> sets it as the current scheme (one value per role) and opens Mouse Properties
                  once (RunOnce) so you can press Apply - that's what makes Windows reload cursors.
The scheme value must list files in roles.ROLES order (17 roles incl. Pin + Person).
"""
from __future__ import annotations

from . import __version__
from .roles import ROLE_BY_KEY, ROLES


def _ext(animated: dict[str, bool], key: str) -> str:
    return "ani" if animated.get(key) else "cur"


def make_inf(scheme_name: str, animated: dict[str, bool]) -> str:
    files = {r.key: f"{r.filename}.{_ext(animated, r.key)}" for r in ROLES}
    def path(k: str) -> str:
        return rf"%10%\%CUR_DIR%\%{ROLE_BY_KEY[k].filename}%"

    scheme_value = ",".join(path(r.key) for r in ROLES)

    lines = [
        f"; Generated by w11cursor {__version__} - do not edit by hand.",
        f"; Right-click -> Install. Installs the '{scheme_name}' pointer scheme.",
        "",
        "[Version]",
        'signature="$CHICAGO$"',
        "",
        "[DefaultInstall]",
        "CopyFiles = Scheme.Cur",
        "AddReg    = Scheme.Reg, Wreg",
        "",
        "[DestinationDirs]",
        'Scheme.Cur = 10,"%CUR_DIR%"',
        "",
        "[Scheme.Reg]",
        rf'HKCU,"Control Panel\Cursors\Schemes","%SCHEME_NAME%",0x00020000,"{scheme_value}"',
        "",
        "[Wreg]",
        r'HKCU,"Control Panel\Cursors",,0x00020000,"%SCHEME_NAME%"',
        r'HKCU,"Control Panel\Cursors","Scheme Source",0x00010001,1',
    ]
    for r in ROLES:
        lines.append(rf'HKCU,"Control Panel\Cursors",{r.reg_value},0x00020000,"{path(r.key)}"')
    lines += [
        r'HKLM,"SOFTWARE\Microsoft\Windows\CurrentVersion\Runonce\Setup\","",,"rundll32.exe shell32.dll,Control_RunDLL main.cpl @0"',
        "",
        "[Scheme.Cur]",
        *[files[r.key] for r in ROLES],
        "",
        "[Strings]",
        f'CUR_DIR     = "Cursors\\{scheme_name}"',
        f'SCHEME_NAME = "{scheme_name}"',
        *[f'{r.filename:<11} = "{files[r.key]}"' for r in ROLES],
        "",
    ]
    return "\r\n".join(lines)


def make_uninstall_cmd(scheme_name: str) -> str:
    return "\r\n".join(
        [
            "@echo off",
            f"rem Removes the '{scheme_name}' scheme registration. Generated by w11cursor.",
            f'reg delete "HKCU\\Control Panel\\Cursors\\Schemes" /v "{scheme_name}" /f',
            "echo.",
            "echo Scheme removed. Opening Mouse Properties - pick another scheme and press Apply.",
            f'echo Then (as admin) delete: %WINDIR%\\Cursors\\{scheme_name}',
            "rundll32.exe shell32.dll,Control_RunDLL main.cpl @1",
            "",
        ]
    )

